"""
Django settings for social_network_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#7q)w^5n%756-$id1y@h-w9!-q@1-rsa2k3r4@6szbe+_ocdor'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True   # це не торогати (в режимі розробки) будем заморачуватись тільки під кінець проекту

APPEND_SLASH = False

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [       # коли створюєш нові додатки їх вписуються тут
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'channels',
    'users',            # Користувачі 
    'posts',            # Пости
    'messaging',        # Повідомлення
    'voice_channels',   # Голосові канали
    'ai',               # Штучний інтелект
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-language',
    'content-language',
    'content-type',
    'expires',
    'ngrok-skip-browser-warning',  # Ваш нестандартний заголовок
    'Authorization',  # Дозволяємо заголовок Authorization
    'X-Requested-With',
    'X-Custom-Header',  # Якщо є ще кастомні заголовки
    'User-Agent',  # Якщо потрібно змінювати User-Agent
]

ROOT_URLCONF = 'social_network_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_network_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'social_network_db_2',    # Назва бази даних   (треба створити вручну в постгрес)
        'USER': 'postgres',             # Ім'я користувача   (скоріш за все в вас так і залишиться postgres)
        'PASSWORD': '4839150',          # Пароль користувача (тут все зрозуміло) 
        'HOST': 'localhost',            # Ім'я хоста         (ті дані які ви вказали в постгрес)
        'PORT': '5432',                 # Порт бази даних    (дивись вище)
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',  # Залиште дефолтний бекенд для інших випадків
]

CORS_ALLOW_ALL_ORIGINS = True # Увага мля це тимчасова позиція тому що, Це небезпечно для продакшну, оскільки будь-хто може надсилати запити до вашого API, а оскільки ми стараємось робити максимально наближене до справжнього повноціного проекту а потім це помінятью

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"  # Тимчасове сховище (пізніше можна підключити Redis)
    }
}

import os
# Створюємо папку для дефолтних (чортових) аватарок, якщо вона не існує 
DEFAULT_AVATAR_DIR = os.path.join(MEDIA_ROOT, 'default', 'default_avatar')
os.makedirs(DEFAULT_AVATAR_DIR, exist_ok=True)

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'generate-recommendations-every-3-days': {
        'task': 'ai.tasks.generate_recommendations_periodically',
        'schedule': crontab(hour=0, day_of_month=range(1, 32, 3)),
    },
}

FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days= 1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

GOOGLE_CLIENT_ID = "787039931575-u6m6gef67qnirlrn4icoonfedbgoigmi.apps.googleusercontent.com"

# Налаштування для API нейромережі Hugging Face
import os
from dotenv import load_dotenv
load_dotenv()
HF_API_TOKEN = os.getenv("DUDOS")

TEST_RUNNER = 'social_network_project.realdb_test_runner.RealDBTestRunner'