# Generated by Django 5.1.4 on 2025-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
