# Generated by Django 5.1.4 on 2024-12-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hashtags',
            field=models.ManyToManyField(to='posts.hashtag'),
        ),
    ]
