# Generated by Django 5.1.4 on 2025-01-08 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_hashtags_customuser_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
